---
- hosts: all
  vars_files:
  - defaults/main.yml
  - vars/main.yml
  tasks:
  - include: tasks/main.yml
  handlers:
  - include: handlers/main.yml
  - name: Restart MongoDB
    service: name=mongod state=restarted
    become: true
