---
- name: Install PIP
  apt: package=python-pip state=present
  become: yes

- name: Install PyMongo
  pip: name=pymongo state=present executable=pip2
  become: yes

- name: Add APT Key
  apt_key: keyserver=keyserver.ubuntu.com id={{ mongodb_keys[mongodb_version] }} state=present
  become: yes

- name: Add APT Repository
  apt_repository:
    repo: "deb http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse"
    state: present
  become: yes

- name: Create Configuration File
  template: src=mongo.conf.j2 dest=/etc/mongod.conf mode=0644
  become: yes
  notify: Restart MongoDB

- name: Install
  apt: package=mongodb-org state=present
  become: yes
  register: mongodb_install

- name: Install Sysfsutils
  apt: name=sysfsutils state=present
  become: yes

- name: Disable Transparent Huge Pages
  lineinfile:
    dest: /etc/sysfs.conf
    line: "{{ item }}"
    state: present
  with_items:
    - kernel/mm/transparent_hugepage/khugepaged/defrag = 0
    - kernel/mm/transparent_hugepage/defrag = never
    - kernel/mm/transparent_hugepage/enabled = never
  become: yes
  notify:
    - Restart Sysfsutils
    - Restart MongoDB

- name: Enable Service
  systemd: name=mongod enabled=yes daemon_reload=yes
  become: yes
  when: ansible_distribution_release != "trusty"

- name: Start Service
  service: name=mongod state=started
  become: yes

- name: Lockdown
  bebat_mongodb_user:
    name:     "{{ db_admin }}"
    password: "{{ db_pass }}"
    database: admin
    state:    present
    roles:    root,backup,restore
  when:
    - mongodb_authorization == 'enabled'
    - mongodb_install is changed
